spring:
  datasource:
    url: jdbc:mysql://${AWESOME_MEDIA_DB_SERVICE_HOST}${AWESOME_MEDIA_DB_SERVICE_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    initialize:  true
    platform: mysql
 
name: miri-default-hi
